### ISSUE TITLE
Dataset application

### ISSUE THREAD

**Issue by Zhongrocky** [Coolshanlan/Coronary-Artery-Segmentation#2]
Dear Mr.author,
  I'm a postgraduate student from Northeast University in Shenyang. My name is Jinzhong Yang. My mentor is Lisheng Xu. I am very interested in the research of the segmentation of coronary. I want to achieve the segmentation of coronary. However, this project lacks the original data set. Is this dataset public? We want to implement this algorithm, please give us some dataset. We only do research and not for commercial use. At your convenience, would you please share dataset about it to me? I hope that we can publish papers together. Thank you a lot!

Best,

Jinzhong Yang .

**Comment by Coolshanlan** [comment]
Hi Pourya, sorry for very late reply.
This project is collaboration between Landseed International Hospital and
National Central University, then it has ended in 2021.
The dataset is owned by the hospital so I can't share with any others
people. Sorry.

Regards,

Coolshan

**Comment by Coolshanlan** [comment]
Hi Zhongrocky, sorry for the late reply.
This project is collaboration between Landseed International Hospital and
National Central University, then it has ended in 2021.
The dataset is owned by the hospital so I can't share with others people, Sorry.

Regards,
Coolshan
